#!/bin/python3
from os import system 
import subprocess
import sys
import argparse


parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('-r', '--reset', action='store_true', 
                    help='rewrite host_file with currently active nodes')
parser.set_defaults(reset=False)
args = parser.parse_args()


def rewrite_lab_state(num_nodes):
    good_nodes = list()
    for i in range(10, 9 + num_nodes):
        cmd = "127x" + str(i) + ".csc.calpoly.edu"
        val = 0
        try:
            val = subprocess.check_output(['ping', '-c 2', cmd])
        except subprocess.CalledProcessError as e:
            continue
        if val is not 0:
            good_nodes.append(cmd)
    hoster = subprocess.check_output(['hostname'])
    hoster = str(hoster, 'utf-8')
    hoster = hoster.rstrip('\n')
    if hoster in good_nodes:
        good_nodes.remove(hoster)
    good_nodes.insert(0, hoster)
    with open('host_file', 'w') as hosts:
        for node in good_nodes:
            hosts.write(node + " slots=6 max-slots=6" + '\n')
    return good_nodes

def main():
    print ("This is a Lab 127 Impromptu Cluster Creator/Manager")
    num_nodes = 0
    while( num_nodes < 1 or num_nodes > 26 ):
        inputs = input ("Enter the number of machines you wish to use (1 to 26): ")
        num_nodes = int(inputs)

    if args.reset:
        alive = rewrite_lab_state(num_nodes)
        print("Using Nodes:");
        for n in alive:
            print(n)



main()
